create table if not exists public.questionnaire_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  language text not null default 'zh-TW',
  schema_version smallint not null default 1,
  response_data jsonb not null,
  constraint questionnaire_language_check check (language in ('zh-TW', 'en')),
  constraint questionnaire_schema_version_check check (schema_version between 1 and 99),
  constraint questionnaire_response_object_check check (jsonb_typeof(response_data) = 'object'),
  constraint questionnaire_response_size_check check (octet_length(response_data::text) <= 100000)
);

alter table public.questionnaire_responses
  add column if not exists schema_version smallint not null default 1;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'questionnaire_language_check') then
    alter table public.questionnaire_responses
      add constraint questionnaire_language_check check (language in ('zh-TW', 'en'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'questionnaire_schema_version_check') then
    alter table public.questionnaire_responses
      add constraint questionnaire_schema_version_check check (schema_version between 1 and 99);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'questionnaire_response_object_check') then
    alter table public.questionnaire_responses
      add constraint questionnaire_response_object_check check (jsonb_typeof(response_data) = 'object');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'questionnaire_response_size_check') then
    alter table public.questionnaire_responses
      add constraint questionnaire_response_size_check check (octet_length(response_data::text) <= 100000);
  end if;
end $$;

alter table public.questionnaire_responses enable row level security;

revoke all on table public.questionnaire_responses from anon, authenticated;
grant insert on table public.questionnaire_responses to anon;

drop policy if exists "Allow anonymous questionnaire submissions"
on public.questionnaire_responses;

create policy "Allow anonymous questionnaire submissions"
on public.questionnaire_responses
for insert
to anon
with check (
  jsonb_typeof(response_data) = 'object'
  and schema_version = 1
);

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_profiles enable row level security;

revoke all on table public.admin_profiles from anon, authenticated;
grant select on table public.admin_profiles to authenticated;
grant select on table public.questionnaire_responses to authenticated;

drop policy if exists "Admins can view their own profile"
on public.admin_profiles;

create policy "Admins can view their own profile"
on public.admin_profiles
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Admins can view questionnaire responses"
on public.questionnaire_responses;

create policy "Admins can view questionnaire responses"
on public.questionnaire_responses
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_profiles
    where admin_profiles.user_id = (select auth.uid())
  )
);
