title: 風城部屋
lang: zh-TW
url: https://gisneyland.github.io
baseurl: ""
description: 新竹在地 LGBTQ+ 社群服務、文化活動與健康資源入口。
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - .github/
  - .hackmd.io/
